[target.x86_64-unknown-linux-musl]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "wget https://github.com/Kitware/CMake/releases/download/v3.30.0/cmake-3.30.0-linux-x86_64.sh",
    "chmod +x cmake-3.30.0-linux-x86_64.sh",
    "./cmake-3.30.0-linux-x86_64.sh --skip-license --prefix=/usr/local",
    "export DEBIAN_FRONTEND=noninteractive",
    "apt-get update",
    "apt-get install -y wget curl ca-certificates default-jdk tzdata make cmake gcc g++ clang libclang-dev llvm-dev zlib1g-dev libbsd-dev uuid-dev libssl-dev pkg-config"
]