[target.x86_64-unknown-linux-musl]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "export DEBIAN_FRONTEND=noninteractive",
    "apt-get update",
#    "apt-get install -y --no-install-recommends wget curl ca-certificates tzdata make cmake gcc g++ clang libclang-dev llvm-dev zlib1g-dev libbsd-dev uuid-dev libssl-dev pkg-config",
    "apt-get install -y --no-install-recommends wget curl ca-certificates tzdata make libbsd-dev uuid-dev libssl-dev pkg-config",
    "wget https://github.com/Kitware/CMake/releases/download/v4.1.0/cmake-4.1.0-linux-x86_64.sh",
    "chmod +x cmake-4.1.0-linux-x86_64.sh",
    "./cmake-4.1.0-linux-x86_64.sh --skip-license --prefix=/usr/local",
    "mkdir -p /usr/local/jdk-23",
    "wget -qO- https://github.com/adoptium/temurin23-binaries/releases/download/jdk-23.0.2+7/OpenJDK23U-jdk_x64_linux_hotspot_23.0.2_7.tar.gz | tar xz --strip-components=1 -C /usr/local/jdk-23",
    "update-alternatives --install /usr/bin/java java /usr/local/jdk-23/bin/java 100",
    "update-alternatives --install /usr/bin/javac javac /usr/local/jdk-23/bin/javac 100",
    "update-alternatives --install /usr/bin/jar jar /usr/local/jdk-23/bin/jar 100",
    "update-alternatives --install /usr/bin/javadoc javadoc /usr/local/jdk-23/bin/javadoc 100",
    "export JAVA_HOME=/usr/local/jdk-23",
    "export PATH=\"/usr/local/jdk-23/bin:$PATH\"",
    "export CC=x86_64-linux-musl-gcc",
    "export AR=x86_64-linux-musl-ar",
    "export RANLIB=x86_64-linux-musl-ranlib",
    "export CFLAGS=\"-static\"",
#    "find / | grep rusteron-archive/aeron",
#    "cd /volume/rusteron-archive/aeron && ./gradlew :aeron-all:build",
#    "cd /volume/rusteron-media-driver/aeron && ./gradlew :aeron-all:build",
#    "cd /volume/rusteron-client/aeron && ./gradlew :aeron-all:build",
]