[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update",
    "apt-get install -y curl linux-libc-dev pkg-config libssl-dev ca-certificates make cmake gcc g++ clang libclang-dev llvm-dev musl-tools musl-dev libbsd-dev uuid-dev default-jdk"
]