[package]
name = "rusteron-archive"
version = "0.1.27"
edition = "2021"
authors = ["Mo Imran <mimran1980@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/mimran1980/rusteron"
homepage = "https://github.com/mimran1980/rusteron"
keywords = ["aeron", "low-latency", "archive", "bindings", "networking"]
categories = ["network-programming"]
documentation = "https://mimran1980.github.io/rusteron/rusteron_archive/index.html"
description = "Extends the Aeron client to include archiving features, such as recording streams and handling replay capabilities. It uses the Aeron C bindings from aeron-archive module."
readme = "README.md"

exclude = [
    "**/.gradle/**",
    "**/aeron/**/build/**",
]

[build-dependencies]
bindgen = {  workspace = true }
cmake = {  workspace = true }
dunce = {  workspace = true }
pkg-config = {  workspace = true }
syn = {  workspace = true }
proc-macro2 = {  workspace = true }
quote = {  workspace = true }
itertools = {  workspace = true }
rusteron-code-gen = {path = "../rusteron-code-gen", version = "0"}

[dev-dependencies]
serial_test = "3.1"

[features]
static = []
