name: CI

on:
  push:    # This triggers the workflow on any push event
  pull_request:  # This triggers the workflow when a pull request is opened, synchronized, or reopened#
#  push:
#    branches: [master, staging, trying]
#  pull_request:
#    branches: [master]

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        features: [default, static]
        rust-version: ["stable", "stable 6 months ago"]

    env:
      feature-flags: ${{ matrix.features != 'default' && format('--features {0}', matrix.features) || '' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust-version }}
          components: clippy, rustfmt

      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y uuid-dev

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check clippy lints
        run: cargo clippy --all ${{ env.feature-flags }} -- --deny warnings

      - name: Build
        run: cargo build --release --verbose ${{ env.feature-flags }}

      - name: Test
        run: cargo test --verbose ${{ env.feature-flags }}


  deploy_docs:
    name: Deploy Rust Docs
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Only deploy docs on pushes to main branch

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustdoc
          toolchain: stable
          profile: complete

      - name: Build documentation
        run: cargo doc --no-deps

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc