name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type (major, minor, patch)"
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  release:
    timeout-minutes: 45
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y uuid-dev

      # Use GitHub Actions cache for Rust dependencies
      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-registry-${{ runner.os }}-

      - name: Cache Cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: cargo-index-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-index-${{ runner.os }}-

      - name: Cache Cargo build artifacts
        uses: actions/cache@v4
        with:
          path: target
          key: cargo-build-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-build-${{ runner.os }}-

      - name: Cache cargo-release binary
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/cargo-release
          key: cargo-release-${{ runner.os }}

      # Optional: Use sccache for faster rebuilds
      - name: Install sccache
        run: |
          curl -fsSLO https://github.com/mozilla/sccache/releases/latest/download/sccache-x86_64-unknown-linux-musl
          chmod +x sccache-x86_64-unknown-linux-musl
          sudo mv sccache-x86_64-unknown-linux-musl /usr/local/bin/sccache

      - name: Set up sccache
        run: echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

      - name: Test with artifacts
        run: |
          cargo test --features precompile,static --workspace -- --nocapture
          git reset --hard HEAD
          git clean -fdx
          

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Run cargo-release for specified version
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          git config --global user.email "mimran1980@gmail.com"
          git config --global user.name "Mo Imran"
          release_type="${{ github.event.inputs.release_type }}"
          cargo release "$release_type" --workspace --execute --no-confirm --verbose --no-verify

      - name: Push new version and tag to GitHub
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          tags: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check docker example builds
        run: |
          cd rusteron-docker-samples
          docker build -t aeron-media-driver aeron-media-driver
          docker build -t rusteron-dummy-example rusteron-dummy-example
